### ISSUE TITLE
Glasser the background of the add-on bar

### ISSUE THREAD

**Issue by Drugoy** [AllSeeingEye/Barlesque#1]
Fx 4's add-on bar on the screenshots of it's concepts had glassed background. And it definitely should be so.
And as I wrote in comments to your extension on AMO - it is possible to do it, but it can't be done with pure CSS (that's why I can't just write a style and use it). It can be done with XUL, e.g. within from an extension, and your extension is exactly styling the add-on bar, so I write this feature request for you.

To make glassed background you have to be familiar with SVG technology and 1 of it's most common filters - gaussian blur. All you need is just to apply at least this filter to the add-on bar.
There are a lot of examples in the Internet describing how to use that filter.
- a pattern like the one used here: http://habrahabr.ru/blogs/webdev/104624/ could make background look like a windows 7 glass background, not just a blur.

**Comment by AllSeeingEye** [comment]
Something like:

-moz-linear-gradient(top -90deg, white, #b0c4de)

should do the trick. Ideally, add-on bar should inherit the styles of user's theme, I think.

**Comment by Drugoy** [comment]
Well, I agree that it should respect themes, but in case the user is using no theme/persona - a glasser background might look awesome.
Or maybe the users with personas/themes will like it too, since anyways we detach that toolbar from the bottom-box element and the picture (if there is one) might look ugly.

**Comment by Drugoy** [comment]
and no, -moz-linear-gradient is not a glass.
Glass background can only be added via SVG.
Unless you mean to use -moz-linear-gradient in addition to background: transparent - haven't check this yet.

**Comment by Drugoy** [comment]
It appeared that you were both right and wrong.
Reaching the transparency effect by using -moz-linear-gradient is possible, but not like in your example.
Though it's easy, so we should try to implement this by the next version. Later this evening I'll PM you with the style needed to insert.
