### ISSUE TITLE
Add a hotkey to expand/collapse the addon-bar

### ISSUE THREAD

**Issue by Drugoy** [AllSeeingEye/Barlesque#11]
Some users work more with a keyboard, than with a mouse.
And of course it would be better, if the hotkey would be configurable.

**Comment by AllSeeingEye** [comment]
Such shortcut is already in place - "Switch on the shortcut to show/hide the add-on bar" in the options.

Or do I miss something?

**Comment by Drugoy** [comment]
Ah... sorry, missed that :)
you may just delete this request.

**Comment by AllSeeingEye** [comment]
No problemo.
