### ISSUE TITLE
Add-on bar is hidden if findbar is shown

### ISSUE THREAD

**Issue by Drugoy** [AllSeeingEye/Barlesque#2]
I think this is a bad behavior, as a user might need find something on the page and look at something on the add-on bar at the same time (though I can't give a you a vivid example of such a situation).
Actually findbar's width can also be set to dynamic (e.g. don't let it eat the whole window's width), and it is quite simple. But there might be a possible overflow of findbar and add-on bar, in case the user has a narrow Fx window, or in case he uses Find Suggest extension ( http://ed.agadak.net/2010/09/find-suggest-words-from-the-page ).
This happens only in these 2 cases, so maybe it's worth adding that as an optional setting, that you can turn on or turn off.

**Comment by AllSeeingEye** [comment]
Targetting the fix for v.1.15.

**Comment by AllSeeingEye** [comment]
Fixed in commit e03eba9a7b5738a5bee3, though I'm yet to test the compatibility with Find Suggest extension.

**Comment by AllSeeingEye** [comment]
Feature released in v1.15.
