### ISSUE TITLE
Sometimes add-on bar is placed above a horizontal scroll, though there is no horizontal scroll

### ISSUE THREAD

**Issue by Drugoy** [AllSeeingEye/Barlesque#3]
I experience this issue with google mail pages: the add-on bar is higher than bottom edge of the content-area, like there should be a horizontal scroll under it (but there isn't!).

**Comment by AllSeeingEye** [comment]
This issue should have been fixed in version 1.14 of Barlesque. Please download it from <a href="https://addons.mozilla.org/en-US/firefox/addon/259879/versions/">this page</a> and write if it is fixed.

**Comment by Drugoy** [comment]
Yeah, it's fixed.
Thanks for targeting me to a newer version - I forgot to check that page first.

**Comment by AllSeeingEye** [comment]
RESOLVED: FIXED in v1.14.
