### ISSUE TITLE
Place button lower for windows 7 users with aero theme.

### ISSUE THREAD

**Issue by Drugoy** [AllSeeingEye/Barlesque#4]
If you are using Windows 7 and using it's "Aero" theme - every window gets a glassed borders to the all sides of it. Bottom glassed border is high enough, so we can have a button to show/ hide add-on bar on it.
This idea was represented on the screenshots of Fx 4's theme concept ( https://jboriss.files.wordpress.com/2010/06/fourth_series.png ). If you manage to implement that - I would suggest you also put the "hide add-on bar" button inside the add-on bar itself. And "show add-on bar" button, of course, should only appear if the bar is hidden and it should be located on the bottom glassed border.

**Comment by AllSeeingEye** [comment]
One problem is that this will look weird for users who're using maximized/full-screen Firefox window. 

There is a lot of discussion on this topic in the comments to the <a href="http://jboriss.wordpress.com/2010/06/16/removing-firefox’s-status-bar-and-rehousing-add-on-icons-part-3-of-2-wut/">original proposal</a> - please read it.

**Comment by Drugoy** [comment]
I think you can track window's state. Then you can just change the button's appearance for that state: let it occupy some space at bottom of content-area. Anyways you'd better restyle the current button's appearance -
1. the add-on bar looks cut when it's shown and the "hide button" is only half of add-on bar's height. I suggest you putting it inside of add-on bar, so it becomes a real part of it and will be as high as add-on bar is (some users do have styles, that change Fx's theme appearance, maybe someone decided to increase/decrease it's height and making the button a part of the bar will not cause any trouble in that case).
2. when add-on bar is hidden - the button should better be changed into the one from the screenshot above: let it be a little wider, but cut it's height maximally, so in case you are on a site that has own toolbar at bottom - you won't miss some button, which can eventually get hidden under the "show add-on bar" button.
