### ISSUE TITLE
Error in the error console

### ISSUE THREAD

**Issue by Drugoy** [AllSeeingEye/Barlesque#5]
Error: doc.documentElement is null
Source File: chrome://barlesque/content/overlay.js
Line: 181

**Comment by AllSeeingEye** [comment]
Can you please write, what version of Barlesque are you using?

**Comment by Drugoy** [comment]
It was 1.12, but now I have updated to 1.14 and I don't have this error yet.

**Comment by AllSeeingEye** [comment]
Okay. I'll keep this issue open for several days - please write if you have it (and on what page, if any).

**Comment by Drugoy** [comment]
I think you can close the issue just now, as that error appeared quite soon after I installed the previous version of the extension. And now I have already surfed through a few sites and there is still not a single error in the console.

**Comment by AllSeeingEye** [comment]
RESOLVED: FIXED in v1.14.
