### ISSUE TITLE
Add an option to set a timer after which the add-on bar will automaically hide self

### ISSUE THREAD

**Issue by Drugoy** [AllSeeingEye/Barlesque#6]
I insist on making this as an option, e.g. if the user doesn't need it - he can turn it off.

**Comment by AllSeeingEye** [comment]
Targetting this for v.1.15.

**Comment by AllSeeingEye** [comment]
Done in commit 0e625e57e8b0ddbab57b.

**Comment by AllSeeingEye** [comment]
Feature released in version 1.15.
