### ISSUE TITLE
The button's position is overflowing both scrollbars

### ISSUE THREAD

**Issue by Drugoy** [AllSeeingEye/Barlesque#7]
It has to be moved a few pixels upper and a few pixels to the left.

**Comment by AllSeeingEye** [comment]
Version? Any chance of screenshot?

**Comment by Drugoy** [comment]
1.14  http://img338.imageshack.us/img338/1381/nunatebescreenshot.png

**Comment by AllSeeingEye** [comment]
Fixed in commit 96353d1d1ee9e8913594. Release due to v1.15.

**Comment by AllSeeingEye** [comment]
Released in v1.15.
